# Generated by Django 4.1.7 on 2023-04-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket_request",
            name="extra_tickets",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ticket_request",
            name="tickets_ordered",
            field=models.IntegerField(default=0),
        ),
    ]
