# Generated by Django 4.1.7 on 2023-04-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0003_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="studentID",
            new_name="sid",
        ),
    ]
