# Generated by Django 4.1.7 on 2023-04-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0005_alter_student_sid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="sid",
            field=models.IntegerField(default=1234567, max_length=7),
        ),
    ]
