# Generated by Django 4.1.7 on 2023-05-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0007_multi_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="multi_user",
            name="destination",
        ),
    ]
